<?php 
$title="Definition of Alahsa";
include 'header.php';
?>
<style> 
    #wrapper{max-width: 1400px; margin: 0 auto}
        body{background-image:  url("img/pp.jpg") }
        #content p{width: 1000px; margin-left: 150px; font-size: 20px}
        #content ul>li{margin-left: 105px; font-size: 20px; list-style: none; margin-bottom: 16px}
</style>
 <div id="content" style=" background-color: beige; width: 1300px; height: 5000px;border-radius: 4%; margin: 0 auto"  >
                <h1 style="margin-left: 500px; color: brown;"><br><br>Definition of Alahsa</h1>  
                <image src="img/hass.jpg" alt="Unesco network" style=" margin-left: 90px; width: 1113px; height: 500px;"/> 
                <p>Basic information about Alahsa (historical, cultural, economic and social)</p>
                <p>Location:</p> 
                <p>-         Alahsa lies to the east of the Kingdom; to the north lie the provinces of Abqaiq, Nairiyah, and the Ulya Village; to the east lie the Arab Gulf, Qatar and the United Arab Emirates, to the south lie Sultanate of Oman, Yemen and Najran and to the west lie Riyadh and Najran.</p> 
                <p>-         Alahsa is considered one of the historical residential areas across ages. The archeological discoveries which are older than five thousand years B C are the best witness.</p> 
                <p>-         Alahsa is characterized by being a historical center for exchanging commercial goods since it is located on the ancient caravan commercial route known as the Spice or Incense Route; the trade then move southwards to Asia and Africa and northwards to Mesopotamia and the Levant</p>  
                <p>-         The total area of Alahsa is 379000 square kilometer representing 20% of the Kingdom area</p> 
                <p>-         Alahsa population is about 896746 people in accordance with the census of 1425 Hijri; it then increased to 1.1 million in 1431 census Hijri corresponding to 4% of the total kingdom population which is 27 million. Alahsa population in 1433 Hijri was estimated to be 1.3 million distributed on 10 cities and 60 villages.</p> 
                <p>-         96.3% of the Alahsa population live inside Alahsa oasis.</p> 
                <p>The historical Importance</p>
                <p>-         Alahsa is considered one of the most ancient cities where a stable civilization was founded; its civilization dates back to 5000 years BC.</p> 
                <p>-         The Canaanites were the first who settled this province 3000 years BC. They came from the middle of the Arabian Peninsula attracted by the fresh springs; from their dynasty the giant Phoenicians descended</p> 
                <p>-          In the first 1000 years BC, the Chaldeans immigrants migrated to the province from Babel. They founded a city close to Al-oqair (Al-ujair) called Al-jarha. It was an important commercial center. Many Arab tribes migrated to the area where the two tribes of Qatha and Al-Azad settled in the beginning of the Christian calendar</p> 
                <p>-         Abdul-Qays tribe also settled there; it was the most famous among the Arab tribes which settled there in the pre-Islamic era; Suq Hajar and Jawatha markets were the most well-known then. When Islam emerged, they were the first to believe in it: Muhammad, the Messenger of God appointed Ala Bin AlHadhrami a governor of the region.</p>
                <p>-         Prophet Muhammad took proper care of the Gulf residents and of the Bahrainis, Alahsa particularly since the prophet realized the importance of the area, its strategic location to the east of the Arabian Peninsula; he established a solid economic base that played an important role in supporting the Islamic State and the spread of Islam to the neighboring countries.</p> 
                <p>-         Ibn Abbas (May Allah bless him) reported that the first Friday prayer was held in Prophet Muhammad Mosque and the second in Abdul Qays Mosque in Jawatha.</p> 
                <p>-         In 317 Hijri, 929 AD, The Garamith built Alahsa city; then the uyunids in, managed to defeat the Garamuth state with the aid of the Abbasid; Bani Amir then ruled in 615 Hijri and their leader was captured by Jurwan family who are followed by Aljabrids in the middle of the ninth Century Hijri; Al-Gamas family then ruled Alahsa followed by the Turks in 927 Hijri; Alahsa is ruled by the Ottmans from 1080 Hijri to 1669 AD when Bani Khalid leaders forced the Ottomans to retreat.</p> 
                <p>-         At the beginning of the 13th C Hijri, Alahsa was ruled by the Saudis until 1233 Hijri, 1818 AC. When the Ottman Empire launched a military expedition by their governor in Egypt, it managed to occupy Alahsa. The district returned to the Saudi rule after a struggle with the Ottman state when the late King Abdul Aziz marched with his army covered by the date palm leaves to Hofuf. At the night 28/5/1331 Hijri, he managed to liberate the city.</p>
                <p>The Cultural and touristic importance of Alahsa</p> 
                <p>Alahsa possesses cultural and heritage resources renowned in the past and the present; they are sources for attracting tourists; the resources also qualify it to become a tourist attraction center with numerous activities and tourist sites. These cultural and touristic resources diversity; they include archeological and historical sites, (castles, fortresses and mosques), natural resources and wild life (parks and lakes), cultural and thought heritage (museums) besides the tourist beaches. The following are the primary sources of attraction:</p> 
                <p>-         Castles and Museums: Ibrahim Castle, Khuzam Castle, Sahud Castle, the Princely School, Al-Quba School, Alahsa National Museum, for Heritage, Al-Naeem Museum and Al-Thamran Museum and Alkhaleefa Museum .</p> 
                <p>-         Hills and mountains: Al-Qara, Abu al-Husais, Abu-Ghanima, Al-Arba'a and Baraiqa.</p>                 
                <p>-         Alahsa National Park for natural and wild life and Al-Asfar Lake .</p>
                <p>-         A number of gardens and public parks amounting to 700000 square meters; the most important of which are: the National Alahsa Park, King Abdulla Park, the Stadium Park, the Custodian of the two holy mosques Park, Ayn Najim Park. The oasis is characterized by the abundance of rare types of animals and plants </p> 
                <p>-         Alahsa is characterized by its beaches that extend to 150 kilometres; the most important of which is Al-Oqair, Salwa, Al-Batha which is considered the most beautiful beach of Saudi Arabia overlooking the Arab Gulf especially the island districts and the natural reserves surrounding Al-Oqair which is a paradise for the migrant birds .</p> 
                <p>-         Alahsa is also generally distinguished for its tourist geographical markets which are close to many tourist markets whether they are Gulf external or internal markets in districts like Riyadh, Qasim, Jawf, the Northern Borders and Najran. One can easily access them from the Gulf states and from the surrounding areas .</p> 
                <p>-         The availability of transportation and communication (railways, road net) which link cities and oasis congregations with the existing archaeological, historical and touristic sites.</p>
                <p>-         The abundance of accommodation facilities in Alahsa such as diverse hostels, two, three and five stars among which is the Intercontinental.</p> 
                <p>-         The presence of touristic sites which are capable of development in the Alahsa centre and its oasis; the most important of which is Alahsa National Park, its total area amounts to more than 50 square kilo meters; it incorporates more than 8 million trees, besides the natural water features, flowing springs, people markets, archaeological sites and people crafts that produce numerous handmade articles, both modern and traditional.</p> 
                <p>-         Countryside Bunkhouses: bunkhouses are abundant in Alahsa metropolis for holiday making, relaxation and amusement; they are provided with swimming pools, and entertainment facilities; their number exceeds 3000.</p> 
                <p>-         Cultural, educational and social activities are copious in Alahsa , traditional villages, craftsmanship, people culture, rest houses and markets especially in Hofuf and Mubarraz; the most distinctive features are</p>
                <p>Traditional villages and countryside bunkhouses</p> 
                <p>In Alahsa, there are many villages that follow the countryside lifestyle; the countryside nature is characterized by calmness and simplicity. A large number of date palm farmers in Alahsa attempted to provide their farms with countryside bunkhouses and rent them to increase income; some of them have swimming pools. The bunkhouses in Alahsa exceed 3000.</p> 
                <p>The People Markets</p> 
                <p>The Date Market: it lies in the Central Market, Ayn Najim. The visitor enjoys looking at the different types of dates Alahsa is famous for. The market is an annual event; the annual size of trade in this market exceeds 200 million Riyal annually. This reflects the status of Alahsa in the area of date production and marketing</p>               
                <p>Al-Qaysaria Bazaar: it is considered one of the most ancient markets that lie to the east of the Arabian Peninsula. It was probably built in 1822; it incorporates about 422 magazines, 177 of which belong to the municipality that rents them. There is a row of shops in enclosed and roofed areas: the market was built after the Ottman style: it was renovated after the fire which engulfed it in 2001. The market attracts many local and foreign tourists by its architecture.</p>
                <p>Al-Swaiq Bazar: it is the most outstanding commercial market for women; it holds a large collection of modern commercial societies which expose a variety of goods and women commodities. It is known for its large size and the variety of its products. It lies in the middle of Al-Hofuf near Al-Qaysaria Market; on one of its sides, lies the Gold and Jewelry Market where there are many special shops for producing gold works for which Alahsa is famous both production wise and marketing wise. Al-Majid street lies in the parallel street which is known for its commercial centers, women cloth shops and international trade marks.</p>
                <p>Goldsmith Market: it lies in the middle of Hofuf; it is a collection of alleys with shops for selling gold</p>
                <p>Coppersmiths Bazar: it is part of Al-Qaysariah; it lies in the Smiths Street where the cooking tools are made as well as the tools for preserving milk along with other products like the famous Hasawi coffee pots</p> 
                <p>The Bedouin Market: it is close to Qaysaria Market in the middle of Hofuf where the sell assistants display the desert necessities: cloths, tents, local ghee and hand-made products. The market is still there; it flourishes during the week days; most of the sellers are women</p>
                <p>The Camel Market: it lies outside Hofuf city, to the west on the Riyadh Road; it is not only limited to camel trading but it also includes the sheep, goats, horses, donkeys and cows: It is a huge market that flourishes on Thursday morning where shopping reaches its climax</p>
                <p>-       Al-Haraj (auction) Market: a huge market held daily whereby sellers expose different types of goods to be auctioned; it lies where Thursday Bazar is held between Hofuf and Mobrraz on the road of King Fahad in Faisaliah. Numerous articles and commodities, both used and new are displayed.</p>
                <p>Recreational Commodity Market: it lies close to Ibrahim Basha Castle whereby diverse local heritage articles are sold; an auction is held weekly every Wednesday (Thursday Eve).</p>                 
                <p>Wednesday Market:it is held in Mubarraz city and it displays different items among which are hand-made crafts for the residents of the north villages; many Bedouins residents of Hajar visit it</p> 
                <p>Thursday Market: it is held in Hofuf; it is the largest of Alahsa markets occupying an area about 4500 square meters. It is held every Thursday morning and it is a continuation of the traditional open markets where the manual local commodities are sold besides the new and imported ones. The different items on display entice the visitors ` appetites; everyone can find what pleases him; it looks like a department store with different sections that overlap with each other.</p>
                <p>Bazars and modern malls: there are many shopping centres and commercial complexes that enclose numerous shops such as the gold smith`s, clothes`and children entertainment places; they are spread all over the Alahsa cities and villages, the largest of which is Al-Othaim Mall, Al-Bustan Complex in Hofuf, Al-Hamra and Alahsa Complex in Mubarraz among others.</p> 
                <p>Crafts and traditional industries: Alahsa in general and Hofuf and Mubarraz in particular are famous for their crafts and traditional industries that are related to the economic activities of the people and their needs (articles and hand-made products in all forms), the most important products are those that deal with the textile industry, goldsmith works, palm branches, wood, blacksmith, copper, ornaments and silver, pottery, mortar and renovating mud buildings. Some of these products are still made at home with the help of women; the most important products are:</p>  
                <p>The coffee pot: it is made of copper; it is a container for making the Arabic coffee; the Alahsa coffee pot is well-known all over the Gulf States for its beauty, design and outlook. The pot makers’ shops are mainly nearby Qaysariah Market in Hofuf; it is displayed with the other copper products like the cooking pots, water containers among others</p> 
                <p>Pottery: the nature of life necessitates the initiation of this industry relying on local mud and producing household commodities such as air coolers, boilers among others. There used to be three workshops in Hofuf, Mubarraz and Qara; but only the one in Qara is in operation for fine works while others for bulk and hard potery these days; Qara was renovated and opened for visitors via a project that belongs to the General Association for Tourism and archaeology.</p>
                <p>Leaves products: there are many products whereby leaves and palm branches are used; the most important of which are the ropes which are made from the palm leaves that are extensively used especially for building, agricultural works, making pillows and cushions that support the back in the Arabian traditional sitting posture; they are stuffed with leaves and placed inside bags beautifully made of cloth. Carpetbag: a pair of a bags laid over the back of animals and used for carrying items; a four-bag bag: it looks like the carpetbag but it consists of four bags, each of which looks like a cone for carrying water pots.</p> 
                <p>Palm-leaves products: the date-palms are the nerve of life in Alahsa and the palm raw products enter into many traditional industries; from the leaves, different products with diverse shapes are made such as mats, food mats, date containers, hand-made airscrews among others. These items have long-life span, when they are manufactured, they are placed in water, dried and dyed with different colours for decoration; they are displayed in the people markets.</p> 
                <p>Al-Sumut: it is the branch of the palm tree free from the leaves; when the leaves are removed, it becomes bare, from which numerous products are made, the most important of which are the date and milk containers and the children beds (Manaz) that are made according to the standard measures and the chicken transport cages (muchabbah) among other items</p> 
                <p>Al-Madad, (Carpets): these are sitting mats; the name is derived from its lengthy extension which sometimes exceeds 10 meters; they are set on the floors of the mosques and meeting places; they are made from a plant known Al-Asal, which is gathered from places where water is abundant in Alahsa such as the Alasfar Lake; they are made artistically mostly by the dwellers of Omran and Qarain Villages.</p>
            </div>  
                     <?php        include 'footer.php';?>
